  en: 'English'
  en_AS: 'English (American Samoa)'
  en_AI: 'English (Anguilla)'
  en_AG: 'English (Antigua & Barbuda)'
  en_AU: 'English (Australia)'
  en_BS: 'English (Bahamas)'
  en_BB: 'English (Barbados)'
  en_BE: 'English (Belgium)'
  en_BZ: 'English (Belize)'
  en_BM: 'English (Bermuda)'
  en_BW: 'English (Botswana)'
  en_IO: 'English (British Indian Ocean Territory)'
  en_VG: 'English (British Virgin Islands)'
  en_CM: 'English (Cameroon)'
  en_CA: 'English (Canada)'
  en_KY: 'English (Cayman Islands)'
  en_CX: 'English (Christmas Island)'
  en_CC: 'English (Cocos (Keeling) Islands)'
  en_CK: 'English (Cook Islands)'
  en_DG: 'English (Diego Garcia)'
  en_DM: 'English (Dominica)'
  en_ER: 'English (Eritrea)'
  en_FK: 'English (Falkland Islands)'
  en_FJ: 'English (Fiji)'
  en_GM: 'English (Gambia)'
  en_GH: 'English (Ghana)'
  en_GI: 'English (Gibraltar)'
  en_GD: 'English (Grenada)'
  en_GU: 'English (Guam)'
  en_GG: 'English (Guernsey)'
  en_GY: 'English (Guyana)'
  en_HK: 'English (Hong Kong SAR China)'
  en_IN: 'English (India)'
  en_IE: 'English (Ireland)'
  en_IM: 'English (Isle of Man)'
  en_JM: 'English (Jamaica)'
  en_JE: 'English (Jersey)'
  en_KE: 'English (Kenya)'
  en_KI: 'English (Kiribati)'
  en_LS: 'English (Lesotho)'
  en_LR: 'English (Liberia)'
  en_MO: 'English (Macau SAR China)'
  en_MG: 'English (Madagascar)'
  en_MW: 'English (Malawi)'
  en_MY: 'English (Malaysia)'
  en_MT: 'English (Malta)'
  en_MH: 'English (Marshall Islands)'
  en_MU: 'English (Mauritius)'
  en_FM: 'English (Micronesia)'
  en_MS: 'English (Montserrat)'
  en_NA: 'English (Namibia)'
  en_NR: 'English (Nauru)'
  en_NZ: 'English (New Zealand)'
  en_NG: 'English (Nigeria)'
  en_NU: 'English (Niue)'
  en_NF: 'English (Norfolk Island)'
  en_MP: 'English (Northern Mariana Islands)'
  en_PK: 'English (Pakistan)'
  en_PW: 'English (Palau)'
  en_PG: 'English (Papua New Guinea)'
  en_PH: 'English (Philippines)'
  en_PN: 'English (Pitcairn Islands)'
  en_PR: 'English (Puerto Rico)'
  en_RW: 'English (Rwanda)'
  en_WS: 'English (Samoa)'
  en_SC: 'English (Seychelles)'
  en_SL: 'English (Sierra Leone)'
  en_SG: 'English (Singapore)'
  en_SX: 'English (Sint Maarten)'
  en_SB: 'English (Solomon Islands)'
  en_ZA: 'English (South Africa)'
  en_SS: 'English (South Sudan)'
  en_SH: 'English (St. Helena)'
  en_KN: 'English (St. Kitts & Nevis)'
  en_LC: 'English (St. Lucia)'
  en_VC: 'English (St. Vincent & Grenadines)'
  en_SD: 'English (Sudan)'
  en_SZ: 'English (Swaziland)'
  en_TZ: 'English (Tanzania)'
  en_TK: 'English (Tokelau)'
  en_TO: 'English (Tonga)'
  en_TT: 'English (Trinidad & Tobago)'
  en_TC: 'English (Turks & Caicos Islands)'
  en_TV: 'English (Tuvalu)'
  en_UM: 'English (U.S. Outlying Islands)'
  en_VI: 'English (U.S. Virgin Islands)'
  en_UG: 'English (Uganda)'
  en_GB: 'English (United Kingdom)'
  en_US: 'English (United States)'
  en_VU: 'English (Vanuatu)'
  en_ZM: 'English (Zambia)'
  en_ZW: 'English (Zimbabwe)'
  pt: 'Portuguese'
  pt_AO: 'Portuguese (Angola)'
  pt_BR: 'Portuguese (Brazil)'
  pt_CV: 'Portuguese (Cape Verde)'
  pt_GW: 'Portuguese (Guinea-Bissau)'
  pt_MO: 'Portuguese (Macau SAR China)'
  pt_MZ: 'Portuguese (Mozambique)'
  pt_PT: 'Portuguese (Portugal)'
  pt_ST: 'Portuguese (São Tomé & Príncipe)'
  pt_TL: 'Portuguese (Timor-Leste)'
  es: 'Spanish'
  es_AR: 'Spanish (Argentina)'
  es_BO: 'Spanish (Bolivia)'
  es_IC: 'Spanish (Canary Islands)'
  es_EA: 'Spanish (Ceuta & Melilla)'
  es_CL: 'Spanish (Chile)'
  es_CO: 'Spanish (Colombia)'
  es_CR: 'Spanish (Costa Rica)'
  es_CU: 'Spanish (Cuba)'
  es_DO: 'Spanish (Dominican Republic)'
  es_EC: 'Spanish (Ecuador)'
  es_SV: 'Spanish (El Salvador)'
  es_GQ: 'Spanish (Equatorial Guinea)'
  es_GT: 'Spanish (Guatemala)'
  es_HN: 'Spanish (Honduras)'
  es_MX: 'Spanish (Mexico)'
  es_NI: 'Spanish (Nicaragua)'
  es_PA: 'Spanish (Panama)'
  es_PY: 'Spanish (Paraguay)'
  es_PE: 'Spanish (Peru)'
  es_PH: 'Spanish (Philippines)'
  es_PR: 'Spanish (Puerto Rico)'
  es_ES: 'Spanish (Spain)'
  es_US: 'Spanish (United States)'
  es_UY: 'Spanish (Uruguay)'
  es_VE: 'Spanish (Venezuela)'